Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000  # app
  config.vm.network "forwarded_port", guest: 9090, host: 9090  # prometheus
  config.vm.network "forwarded_port", guest: 3001, host: 3001  # cadvisor (optional)
  config.vm.network "forwarded_port", guest: 9100, host: 9100  # node_exporter (if using host)
  config.vm.network "forwarded_port", guest: 9093, host: 9093  # alertmanager
  config.vm.network "forwarded_port", guest: 3002, host: 3002  # grafana

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision/bootstrap.sh"
end
